packages:
  - "backends/node/shared/*"
  - "backends/node/shared/implementations/**"
  - "backends/node/services/*"
  - "clients/web"

onlyBuiltDependencies:
  - "@bufbuild/buf"
  - "@tailwindcss/oxide"
  - esbuild
  - protobufjs
