@ApiService_HostAddress = http://localhost:5461

### Get full geographic reference data
GET {{ApiService_HostAddress}}/api/v1/geo/reference-data
Accept: application/json

### Get geographic reference data version
GET {{ApiService_HostAddress}}/api/v1/geo/reference-data/version
Accept: application/json
