// <auto-generated />
using System;
using D2.Geo.Infra.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace D2.Geo.Infra.Repository.Migrations
{
    [DbContext(typeof(GeoDbContext))]
    [Migration("20251123143456_AddRefDataVersion")]
    partial class AddRefDataVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("D2.Geo.Domain.Entities.Country", b =>
                {
                    b.Property<string>("ISO31661Alpha2Code")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("iso_3166_1_alpha_2_code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<string>("ISO31661Alpha3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("iso_3166_1_alpha_3_code");

                    b.Property<string>("ISO31661NumericCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("iso_3166_1_numeric_code");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("official_name");

                    b.Property<string>("PhoneNumberFormat")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number_format");

                    b.Property<string>("PhoneNumberPrefix")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("phone_number_prefix");

                    b.Property<string>("PrimaryCurrencyISO4217AlphaCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("primary_currency_iso_4217_alpha_code");

                    b.Property<string>("PrimaryLocaleIETFBCP47Tag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("primary_locale_ietf_bcp_47_tag");

                    b.Property<string>("SovereignISO31661Alpha2Code")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("sovereign_iso_3166_1_alpha_2_code");

                    b.HasKey("ISO31661Alpha2Code");

                    b.HasIndex("ISO31661Alpha3Code")
                        .IsUnique();

                    b.HasIndex("ISO31661NumericCode")
                        .IsUnique();

                    b.HasIndex("PrimaryCurrencyISO4217AlphaCode");

                    b.HasIndex("PrimaryLocaleIETFBCP47Tag");

                    b.HasIndex("SovereignISO31661Alpha2Code");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("D2.Geo.Domain.Entities.Currency", b =>
                {
                    b.Property<string>("ISO4217AlphaCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("iso_4217_alpha_code");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer")
                        .HasColumnName("decimal_places");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<string>("ISO4217NumericCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("iso_4217_numeric_code");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("official_name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("symbol");

                    b.HasKey("ISO4217AlphaCode");

                    b.HasIndex("ISO4217NumericCode")
                        .IsUnique();

                    b.ToTable("currencies", (string)null);
                });

            modelBuilder.Entity("D2.Geo.Domain.Entities.GeopoliticalEntity", b =>
                {
                    b.Property<string>("ShortCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("short_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("ShortCode");

                    b.ToTable("geopolitical_entities", (string)null);
                });

            modelBuilder.Entity("D2.Geo.Domain.Entities.Language", b =>
                {
                    b.Property<string>("ISO6391Code")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("iso_639_1_code");

                    b.Property<string>("Endonym")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("endonym");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("ISO6391Code");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("D2.Geo.Domain.Entities.Locale", b =>
                {
                    b.Property<string>("IETFBCP47Tag")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("ietf_bcp_47_tag");

                    b.Property<string>("CountryISO31661Alpha2Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_iso_3166_1_alpha_2_code");

                    b.Property<string>("Endonym")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("endonym");

                    b.Property<string>("LanguageISO6391Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language_iso_639_1_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("IETFBCP47Tag");

                    b.HasIndex("CountryISO31661Alpha2Code");

                    b.HasIndex("LanguageISO6391Code");

                    b.ToTable("locales", (string)null);
                });

            modelBuilder.Entity("D2.Geo.Domain.Entities.Subdivision", b =>
                {
                    b.Property<string>("ISO31662Code")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("iso_3166_2_code");

                    b.Property<string>("CountryISO31661Alpha2Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_iso_3166_1_alpha_2_code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("official_name");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("short_code");

                    b.HasKey("ISO31662Code");

                    b.HasIndex("CountryISO31661Alpha2Code");

                    b.ToTable("subdivisions", (string)null);
                });

            modelBuilder.Entity("D2.Geo.Infra.Repository.Entities.ReferenceDataVersion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("reference_data_version", (string)null);
                });

            modelBuilder.Entity("country_currencies", b =>
                {
                    b.Property<string>("country_iso_3166_1_alpha_2_code")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("currency_iso_4217_alpha_code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("country_iso_3166_1_alpha_2_code", "currency_iso_4217_alpha_code");

                    b.HasIndex("currency_iso_4217_alpha_code");

                    b.ToTable("country_currencies");
                });

            modelBuilder.Entity("country_geopolitical_entities", b =>
                {
                    b.Property<string>("country_iso_3166_1_alpha_2_code")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("geopolitical_entity_short_code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("country_iso_3166_1_alpha_2_code", "geopolitical_entity_short_code");

                    b.HasIndex("geopolitical_entity_short_code");

                    b.ToTable("country_geopolitical_entities");
                });

            modelBuilder.Entity("D2.Geo.Domain.Entities.Country", b =>
                {
                    b.HasOne("D2.Geo.Domain.Entities.Currency", "PrimaryCurrency")
                        .WithMany()
                        .HasForeignKey("PrimaryCurrencyISO4217AlphaCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("D2.Geo.Domain.Entities.Locale", "PrimaryLocale")
                        .WithMany()
                        .HasForeignKey("PrimaryLocaleIETFBCP47Tag")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("D2.Geo.Domain.Entities.Country", "SovereignCountry")
                        .WithMany("Territories")
                        .HasForeignKey("SovereignISO31661Alpha2Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrimaryCurrency");

                    b.Navigation("PrimaryLocale");

                    b.Navigation("SovereignCountry");
                });

            modelBuilder.Entity("D2.Geo.Domain.Entities.Locale", b =>
                {
                    b.HasOne("D2.Geo.Domain.Entities.Country", "Country")
                        .WithMany("Locales")
                        .HasForeignKey("CountryISO31661Alpha2Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("D2.Geo.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageISO6391Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("D2.Geo.Domain.Entities.Subdivision", b =>
                {
                    b.HasOne("D2.Geo.Domain.Entities.Country", "Country")
                        .WithMany("Subdivisions")
                        .HasForeignKey("CountryISO31661Alpha2Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("country_currencies", b =>
                {
                    b.HasOne("D2.Geo.Domain.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("country_iso_3166_1_alpha_2_code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D2.Geo.Domain.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("currency_iso_4217_alpha_code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("country_geopolitical_entities", b =>
                {
                    b.HasOne("D2.Geo.Domain.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("country_iso_3166_1_alpha_2_code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D2.Geo.Domain.Entities.GeopoliticalEntity", null)
                        .WithMany()
                        .HasForeignKey("geopolitical_entity_short_code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("D2.Geo.Domain.Entities.Country", b =>
                {
                    b.Navigation("Locales");

                    b.Navigation("Subdivisions");

                    b.Navigation("Territories");
                });
#pragma warning restore 612, 618
        }
    }
}
