@ApiService_HostAddress = http://localhost:5461

### Get full geographic reference data (via local)
GET {{ApiService_HostAddress}}/api/v1/geo/reference-data
Accept: application/json

### Get full geographic reference data (via cloudflared)
GET https://t-d2-rest.dcsv.io/api/v1/geo/reference-data
Accept: application/json

### Request geographic reference data update
POST {{ApiService_HostAddress}}/api/v1/geo/reference-data/update
Accept: application/json
